-- AlterTable
ALTER TABLE `Customer` ADD COLUMN `creditBalance` DOUBLE NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `Payment` ADD COLUMN `appliedToDebt` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `creditAmount` DOUBLE NOT NULL DEFAULT 0;
